services:
  - type: pserv
    name: banking-db
    plan: starter
    databaseName: bank
    user: postgres

  - type: web
    name: banking-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    healthCheckPath: "/health"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "721c12b9e2512ff9a7409b51382f770231d5f33dfbcd725e"
      - key: ENCRYPTION_KEY
        value: "Bc0TG0ffA8HHhFBVnYZfsGy5sU7IXipXBprTBzvoxXk="
      - key: DATABASE_URL
        fromDatabase:
          name: banking-db
          property: connectionString
      - key: REDIS_URL
        value: "memory://"
      - key: RECAPTCHA_SITE_KEY
        value: "6LcRFZArAAAAAM0cTxjEnnAsHnywGq030LSJV6qE"
      - key: RECAPTCHA_SECRET_KEY
        value: "6LcRFZArAAAAAMMrUkZeDuZUCzAKKGOtsUNA4BKW"
      - key: MAIL_SERVER
        value: "smtp.gmail.com"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USE_SSL
        value: "False"
      - key: MAIL_USERNAME
        value: "krishna.gupta3657@gmail.com"
      - key: MAIL_PASSWORD
        value: "xyrt vjye rjgj tess"
